# Generated by Django 5.0.1 on 2026-01-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20251230_0010'),
        ('core', '0011_merge_20251230_0029'),
    ]

    operations = [
    ]
