# Generated by Django 5.0.1 on 2026-01-01 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20260101_0820'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL for action button', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('comment_added', 'Comment Added'), ('project_updated', 'Project Updated'), ('team_member_added', 'Team Member Added'), ('deadline_approaching', 'Deadline Approaching'), ('milestone_reached', 'Milestone Reached'), ('mention', 'Mention')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='blocker_reason',
            field=models.TextField(blank=True, help_text='Reason why task is blocked', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable email notifications'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('team_member', 'Team Member'), ('developer', 'Developer'), ('viewer', 'Viewer'), ('recruitment_agent', 'Recruitment Agent'), ('frontline_agent', 'Frontline Agent'), ('marketing_agent', 'Marketing Agent')], default='team_member', max_length=20),
        ),
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('view_type', models.CharField(choices=[('list', 'List View'), ('kanban', 'Kanban Board'), ('calendar', 'Calendar View'), ('gantt', 'Gantt Chart')], default='list', max_length=20)),
                ('filters_json', models.JSONField(blank=True, default=dict, help_text='Stored filter criteria')),
                ('columns_json', models.JSONField(blank=True, default=dict, help_text='Column configuration')),
                ('is_default', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(help_text='e.g., task_assigned, task_reminder, milestone_reminder', max_length=50)),
                ('subject_template', models.CharField(max_length=255)),
                ('body_html_template', models.TextField(blank=True, null=True)),
                ('body_text_template', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'template_type')},
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.taskcomment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.taskcomment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='core.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('billable', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_entries', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('task_due', 'Task Due Date'), ('task_assigned', 'Task Assigned'), ('milestone_due', 'Milestone Due Date'), ('meeting_upcoming', 'Meeting Upcoming'), ('task_overdue', 'Task Overdue')], max_length=50)),
                ('reminder_time', models.DateTimeField(help_text='When to send the reminder')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='core.meeting')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='core.projectmilestone')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='core.task')),
            ],
            options={
                'ordering': ['reminder_time'],
                'indexes': [models.Index(fields=['status', 'reminder_time'], name='core_emailr_status_5ab834_idx'), models.Index(fields=['reminder_type', 'status'], name='core_emailr_reminde_7f0496_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='e.g., Task, Project, Meeting', max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailtemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', '-sent_at'], name='core_emaill_recipie_a08f9d_idx'), models.Index(fields=['status', '-sent_at'], name='core_emaill_status_cad20f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('comment_added', 'Comment Added'), ('project_updated', 'Project Updated'), ('team_member_added', 'Team Member Added'), ('deadline_approaching', 'Deadline Approaching'), ('daily_digest', 'Daily Digest'), ('weekly_digest', 'Weekly Digest')], max_length=50)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(default='immediate', help_text='immediate, daily, weekly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'notification_type'],
                'unique_together': {('user', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='ProjectHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('overall_score', models.IntegerField(help_text='Score 0-100')),
                ('budget_score', models.IntegerField(blank=True, help_text='Score 0-100', null=True)),
                ('timeline_score', models.IntegerField(blank=True, help_text='Score 0-100', null=True)),
                ('resource_score', models.IntegerField(blank=True, help_text='Score 0-100', null=True)),
                ('quality_score', models.IntegerField(blank=True, help_text='Score 0-100', null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='core.project')),
            ],
            options={
                'ordering': ['-date', '-calculated_at'],
                'indexes': [models.Index(fields=['project', '-date'], name='core_projec_project_32b489_idx')],
                'unique_together': {('project', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.project')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='core.task')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='core_projec_project_3cc81c_idx'), models.Index(fields=['status', '-created_at'], name='core_projec_status_99e7c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('probability', models.IntegerField(default=50, help_text='Probability percentage 0-100')),
                ('impact', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('monitoring', 'Monitoring'), ('mitigating', 'Mitigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='identified', max_length=20)),
                ('mitigation_plan', models.TextField(blank=True, null=True)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_risks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_risks', to='core.task')),
            ],
            options={
                'ordering': ['-severity', '-identified_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='core_projec_project_19f1d3_idx'), models.Index(fields=['severity', 'status'], name='core_projec_severit_0fd385_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('due_date_changed', 'Due Date Changed'), ('priority_changed', 'Priority Changed'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('completed', 'Completed'), ('reopened', 'Reopened')], max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='core_taskac_task_id_201582_idx'), models.Index(fields=['user', '-created_at'], name='core_taskac_user_id_97b74b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=50)),
                ('download_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='core_taskat_task_id_a92380_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', '-created_at'], name='core_taskco_task_id_2f65f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktag',
            unique_together={('name', 'project')},
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['task', '-date'], name='core_timeen_task_id_2fdd27_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', '-date'], name='core_timeen_user_id_dcc163_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['date', 'user'], name='core_timeen_date_6f2217_idx'),
        ),
        migrations.AddIndex(
            model_name='timersession',
            index=models.Index(fields=['user', 'is_active'], name='core_timers_user_id_11c1c0_idx'),
        ),
    ]
