# Generated by Django 5.0.1 on 2026-01-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_phone_number_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_reasoning',
            field=models.TextField(blank=True, help_text='AI-generated reasoning and implementation suggestions for this task', null=True),
        ),
    ]
