# Generated by Django 5.0.1 on 2026-01-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_userprofile_role'),
        ('core', '0016_task_ai_reasoning'),
    ]

    operations = [
    ]
