# Generated by Django 5.0.1 on 2026-01-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20260105_2329'),
        ('core', '0017_merge_20260106_0106'),
        ('core', '0017_merge_20260106_1638'),
    ]

    operations = [
    ]
