# Generated by Django 5.0.1 on 2026-01-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20260109_0814'),
        ('core', '0019_merge_20260109_2324'),
        ('core', '0019_merge_20260113_0127'),
    ]

    operations = [
    ]
