# Generated by Django 5.0.1 on 2026-01-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20260109_2324'),
        ('core', '0019_merge_20260113_0127'),
        ('core', '0025_remove_project_company_user_manager_and_more'),
    ]

    operations = [
    ]
