# Generated by Django 4.2.7 on 2026-01-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20260116_2253'),
        ('core', '0026_merge_20260119_1539'),
    ]

    operations = [
    ]
