# Generated by Django 5.0.1 on 2026-01-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0008_interview_followup_delay_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='followup_count',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='followup_delay_hours',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='last_followup_sent_at',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='max_followup_emails',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='min_hours_between_followups',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='pre_interview_reminder_sent_at',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='reminder_hours_before',
        ),
        migrations.DeleteModel(
            name='RecruiterEmailSettings',
        ),
    ]
