# Generated by Django 5.0.1 on 2026-01-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0010_add_missing_followup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='followup_delay_hours',
            field=models.FloatField(default=48, help_text='Hours to wait before sending first follow-up email (e.g., 0.1 = 6 minutes)'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='min_hours_between_followups',
            field=models.FloatField(default=24, help_text='Minimum hours between follow-up emails (e.g., 0.1 = 6 minutes)'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='reminder_hours_before',
            field=models.FloatField(default=24, help_text='Hours before scheduled interview to send reminder (e.g., 0.5 = 30 minutes)'),
        ),
        migrations.AlterField(
            model_name='recruiteremailsettings',
            name='followup_delay_hours',
            field=models.FloatField(default=48, help_text='Hours to wait before sending first follow-up email (e.g., 0.1 = 6 minutes, 1 = 1 hour)'),
        ),
        migrations.AlterField(
            model_name='recruiteremailsettings',
            name='min_hours_between_followups',
            field=models.FloatField(default=24, help_text='Minimum hours between follow-up emails (e.g., 0.1 = 6 minutes, 1 = 1 hour)'),
        ),
        migrations.AlterField(
            model_name='recruiteremailsettings',
            name='reminder_hours_before',
            field=models.FloatField(default=24, help_text='Hours before scheduled interview to send reminder (e.g., 0.5 = 30 minutes, 1 = 1 hour)'),
        ),
    ]
