# Generated by Django 5.0.1 on 2026-01-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0013_add_company_user_to_job_description'),
        ('recruitment_agent', '0014_recruiterinterviewsettings_time_slots_json'),
    ]

    operations = [
    ]
