# Generated by Django 5.0.1 on 2026-01-19 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20260119_1539'),
        ('recruitment_agent', '0015_merge_20260119_1539'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='company_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_interviews_company', to='core.companyuser'),
        ),
        migrations.AddField(
            model_name='recruiteremailsettings',
            name='company_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_email_settings_company', to='core.companyuser'),
        ),
        migrations.AddField(
            model_name='recruiterinterviewsettings',
            name='company_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_interview_settings_company', to='core.companyuser'),
        ),
        migrations.AlterField(
            model_name='recruiteremailsettings',
            name='recruiter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_email_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruiterinterviewsettings',
            name='recruiter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_interview_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
