# Generated by Django 5.0.1 on 2026-01-07 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0018_add_interest_level_to_sub_sequences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_subject', models.CharField(blank=True, max_length=500)),
                ('reply_content', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interest_level', models.CharField(choices=[('positive', 'Positive/Interested'), ('negative', 'Negative/Not Interested'), ('neutral', 'Neutral'), ('requested_info', 'Requested More Information'), ('objection', 'Has Objection/Concern'), ('unsubscribe', 'Unsubscribe Request'), ('not_analyzed', 'Not Analyzed')], default='not_analyzed', max_length=20)),
                ('analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='marketing_agent.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='marketing_agent.campaigncontact')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='marketing_agent.lead')),
                ('triggering_email', models.ForeignKey(blank=True, help_text='The email that this reply was responding to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_replies', to='marketing_agent.emailsendhistory')),
            ],
            options={
                'ordering': ['-replied_at'],
                'indexes': [models.Index(fields=['contact', '-replied_at'], name='marketing_a_contact_1e9b29_idx'), models.Index(fields=['campaign', '-replied_at'], name='marketing_a_campaig_75326a_idx'), models.Index(fields=['lead', '-replied_at'], name='marketing_a_lead_id_cbaaf3_idx')],
            },
        ),
    ]
