# Generated by Django 5.0.1 on 2026-01-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0019_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='sequence',
            field=models.ForeignKey(blank=True, help_text='The sequence that the replied-to email belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='marketing_agent.emailsequence'),
        ),
        migrations.AddField(
            model_name='reply',
            name='sub_sequence',
            field=models.ForeignKey(blank=True, help_text='The sub-sequence that the replied-to email belongs to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_sequence_replies', to='marketing_agent.emailsequence'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['sequence', '-replied_at'], name='marketing_a_sequenc_f2638b_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['campaign', 'sequence', '-replied_at'], name='marketing_a_campaig_b0ae7b_idx'),
        ),
    ]
